name: Package Distribution Artifacts

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package_app:
    strategy:
      matrix:
        configuration:
          [
            { runner: "macos-15-intel", format: "dmg", path: "target/release/bundle/dmg/Factr.dmg" },
            { runner: "macos-15", format: "dmg", path: "target/release/bundle/dmg/Factr.dmg" },
            { runner: "windows-2022", format: "exe", path: "target/release/bundle/exe/*.exe" },
            { runner: "ubuntu-latest", format: "appimage", path: "target/release/bundle/appimage/*.AppImage" },
          ]
    runs-on: ${{ matrix.configuration.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Install Bundler
        run: cargo install cargo-bundle
      - name: Install Bundler
        run: cargo bundle --format ${{ matrix.configuration.format }} --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Factr_${{ runner.os }}-${{ runner.arch }}
          path: ${{ matrix.configuration.path }}
